
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;
	
	private global::Gtk.Button _cancel;
	
	private global::Gtk.Entry _data;
	
	private global::Gtk.FileChooserButton _filename;
	
	private global::Gtk.Entry _name;
	
	private global::Gtk.Button _ok;
	
	private global::Gtk.Entry _pass;
	
	private global::Gtk.Entry _server;
	
	private global::Gtk.Button _test;
	
	private global::Gtk.Entry _user;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView _preview;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MySQL To Entity For Mono");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(10)), ((uint)(5)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this._cancel = new global::Gtk.Button ();
		this._cancel.CanFocus = true;
		this._cancel.Name = "_cancel";
		this._cancel.UseUnderline = true;
		this._cancel.Label = global::Mono.Unix.Catalog.GetString ("キャンセル");
		global::Gtk.Image w1 = new global::Gtk.Image ();
		w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
		this._cancel.Image = w1;
		this.table1.Add (this._cancel);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this._cancel]));
		w2.TopAttach = ((uint)(6));
		w2.BottomAttach = ((uint)(7));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._data = new global::Gtk.Entry ();
		this._data.CanFocus = true;
		this._data.Name = "_data";
		this._data.IsEditable = true;
		this._data.InvisibleChar = '●';
		this.table1.Add (this._data);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this._data]));
		w3.TopAttach = ((uint)(4));
		w3.BottomAttach = ((uint)(5));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._filename = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("ファイルを選択"), ((global::Gtk.FileChooserAction)(0)));
		this._filename.Name = "_filename";
		this.table1.Add (this._filename);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this._filename]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._name = new global::Gtk.Entry ();
		this._name.CanFocus = true;
		this._name.Name = "_name";
		this._name.IsEditable = true;
		this._name.InvisibleChar = '●';
		this.table1.Add (this._name);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this._name]));
		w5.TopAttach = ((uint)(5));
		w5.BottomAttach = ((uint)(6));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(4));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._ok = new global::Gtk.Button ();
		this._ok.CanFocus = true;
		this._ok.Name = "_ok";
		this._ok.UseUnderline = true;
		this._ok.Label = global::Mono.Unix.Catalog.GetString ("OK");
		global::Gtk.Image w6 = new global::Gtk.Image ();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Menu);
		this._ok.Image = w6;
		this.table1.Add (this._ok);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this._ok]));
		w7.TopAttach = ((uint)(6));
		w7.BottomAttach = ((uint)(7));
		w7.LeftAttach = ((uint)(3));
		w7.RightAttach = ((uint)(4));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._pass = new global::Gtk.Entry ();
		this._pass.CanFocus = true;
		this._pass.Name = "_pass";
		this._pass.IsEditable = true;
		this._pass.Visibility = false;
		this._pass.InvisibleChar = '●';
		this.table1.Add (this._pass);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this._pass]));
		w8.TopAttach = ((uint)(3));
		w8.BottomAttach = ((uint)(4));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._server = new global::Gtk.Entry ();
		this._server.CanFocus = true;
		this._server.Name = "_server";
		this._server.IsEditable = true;
		this._server.InvisibleChar = '●';
		this.table1.Add (this._server);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this._server]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._test = new global::Gtk.Button ();
		this._test.CanFocus = true;
		this._test.Name = "_test";
		this._test.UseUnderline = true;
		this._test.Label = global::Mono.Unix.Catalog.GetString ("接続テスト");
		global::Gtk.Image w10 = new global::Gtk.Image ();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this._test.Image = w10;
		this.table1.Add (this._test);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this._test]));
		w11.TopAttach = ((uint)(6));
		w11.BottomAttach = ((uint)(7));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._user = new global::Gtk.Entry ();
		this._user.CanFocus = true;
		this._user.Name = "_user";
		this._user.IsEditable = true;
		this._user.InvisibleChar = '●';
		this.table1.Add (this._user);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this._user]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this._preview = new global::Gtk.TextView ();
		this._preview.CanFocus = true;
		this._preview.Name = "_preview";
		this._preview.WrapMode = ((global::Gtk.WrapMode)(2));
		this._preview.Indent = 4;
		this.GtkScrolledWindow.Add (this._preview);
		this.table1.Add (this.GtkScrolledWindow);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow]));
		w14.TopAttach = ((uint)(7));
		w14.BottomAttach = ((uint)(9));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(4));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("MySQL Model");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("MySQL Server");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("User ID");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
		w18.TopAttach = ((uint)(3));
		w18.BottomAttach = ((uint)(4));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Database");
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w19.TopAttach = ((uint)(4));
		w19.BottomAttach = ((uint)(5));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString (" ");
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w20.LeftAttach = ((uint)(4));
		w20.RightAttach = ((uint)(5));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Preview");
		this.table1.Add (this.label7);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
		w21.TopAttach = ((uint)(7));
		w21.BottomAttach = ((uint)(9));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Namespace");
		this.table1.Add (this.label8);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
		w22.TopAttach = ((uint)(5));
		w22.BottomAttach = ((uint)(6));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 561;
		this.DefaultHeight = 403;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this._test.Clicked += new global::System.EventHandler (this.OnTestClicked);
		this._ok.Clicked += new global::System.EventHandler (this.OnOkClicked);
		this._filename.SelectionChanged += new global::System.EventHandler (this.OnFilenameSelectionChanged);
	}
}
